### ISSUE TITLE
Unexpected error: xodBuffer is empty

### ISSUE THREAD

**Issue by Midige** [Nickieros/XOD2XPS-decryption#12]
Hi Nickieros,
Is there any solution to the "Unexpected error: xodBuffer is empty" message?
TIA

**Comment by Nickieros** [comment]
Hi Midige, thank you for bug reporting

The bug is confirmed and fixed (extra folder was hardcoded in the path). Also I added the demo files with password 'foobar12'.
Please update your local app and try it again.

**Comment by Midige** [comment]
Hi Nickieros,

It works perfectly now.
Thank you so much for this fix.
